version: '3'

services:
    base-ros:
        build:
            context: .
            dockerfile: Dockerfile.base
            args:
                - ROS_DISTRO=melodic 
        image: prachandabhanu/env:ros-melodic-robot

    ros-fri:
        build: 
            context: .
            dockerfile: Dockerfile.fri
            args: 
                - ROS_DISTRO=melodic
                - BASE_IMAGE=prachandabhanu/env:ros-melodic-robot
        image: prachandabhanu/env:ros-fri
    
    ros-kuka:
        build: 
            context: .
            dockerfile: Dockerfile.kuka
            args: 
                - ROS_DISTRO=melodic
                - BASE_IMAGE=prachandabhanu/env:ros-fri
        image: prachandabhanu/env:ros-kuka
        stdin_open: true
        tty: true