ARG ROS_DISTRO=melodic
FROM ros:${ROS_DISTRO}-robot

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /root

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update && apt-get -y upgrade \
    && apt-get clean

RUN apt-get -y install vim \
    git \
    python-pip 

RUN pip install -U catkin_tools
    
ENTRYPOINT [ "/ros_entrypoint.sh" ]