version: '3'

services: 
    
    kuka-ros:
        build: 
            context: .
            dockerfile: Dockerfile.kuka
            args: 
                - ROS_DISTRO=melodic
                - BASE_IMAGE=prachandabhanu/env:kuka-fri
        image: prachandabhanu/env:kuka-ros