ARG BASE_IMAGE=prachandabhabu/env:melodic-robot

FROM ${BASE_IMAGE}

RUN mkdir -p ~/catkin_ws/src

RUN cd ~/catkin_ws/src \
    && git clone --recurse-submodules https://github.com/LernFabrik/kuka_iiwa7_ros.git 

RUN rosdep update

RUN echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc

RUN cd ~/catkin_ws \
    && rosdep install --ignore-src --from-paths src -y\
    && ls -a \
    && catkin build

